
define(['easel/models/SoundBoard'], function(soundBoard) {
	
	var init = function() {
		
		soundBoard.loadSounds([
		                      { path: 'sounds/_perc1/1.mp3', name: 'Perc 1' }, 
		                      { path: 'sounds/_perc1/2.mp3', name: 'Perc 2' }, 
		                      // { path: 'sounds/_perc1/3.mp3', name: 'Perc 3' }, 
		                      // { path: 'sounds/_perc1/4.mp3', name: 'Perc 4' }, 
		                      // { path: 'sounds/_perc1/5.mp3', name: 'Perc 5' }, 
		                      // { path: 'sounds/_perc1/6.mp3', name: 'Perc 6' }, 
		                      // { path: 'sounds/_perc1/7.mp3', name: 'Perc 7' }, 
		                      // { path: 'sounds/_perc1/8.mp3', name: 'Perc 8' }, 
		                      // { path: 'sounds/_perc1/9.mp3', name: 'Perc 9' }, 
		                      // { path: 'sounds/_perc1/10.mp3', name: 'Perc 10' }, 
		                      // { path: 'sounds/_perc1/11.mp3', name: 'Perc 11' }, 
		                      // { path: 'sounds/_perc1/12.mp3', name: 'Perc 12' }, 
		                      // { path: 'sounds/_perc1/13.mp3', name: 'Perc 13' }, 
		                      
		                      { path: 'sounds/_synth2/1.mp3', name: 'Synth 1' }, 
		                      { path: 'sounds/_synth2/2.mp3', name: 'Synth 2' }, 
		                      { path: 'sounds/_synth2/3.mp3', name: 'Synth 3' }, 
		                      { path: 'sounds/_synth2/4.mp3', name: 'Synth 4' }, 
		                      { path: 'sounds/_synth2/5.mp3', name: 'Synth 5' }, 
		                      { path: 'sounds/_synth2/6.mp3', name: 'Synth 6' }, 
		                      { path: 'sounds/_synth2/7.mp3', name: 'Synth 7' }, 
		                      { path: 'sounds/_synth2/8.mp3', name: 'Synth 8' }, 
		                      { path: 'sounds/_synth2/9.mp3', name: 'Synth 9' }, 
		                      { path: 'sounds/_synth2/10.mp3', name: 'Synth 10' }, 
		                      { path: 'sounds/_synth2/11.mp3', name: 'Synth 11' }, 
		                      // { path: 'sounds/_synth2/12.mp3', name: 'Synth 12' }, 
		                      // { path: 'sounds/_synth2/13.mp3', name: 'Synth 13' }, 
		                      
		                      // { path: 'sounds/_synth1/1.mp3', name: 'Synth 1' },
		                      // { path: 'sounds/_synth1/2.mp3', name: 'Synth 2' },
		                      // { path: 'sounds/_synth1/3.mp3', name: 'Synth 3' },
		                      // { path: 'sounds/_synth1/4.mp3', name: 'Synth 4' },
		                      // { path: 'sounds/_synth1/5.mp3', name: 'Synth 5' },
		                      // { path: 'sounds/_synth1/6.mp3', name: 'Synth 6' }, 
		                      // { path: 'sounds/_synth1/7.mp3', name: 'Synth 7' }, 
		                      // { path: 'sounds/_synth1/8.mp3', name: 'Synth 8' }, 
		                      // { path: 'sounds/_synth1/9.mp3', name: 'Synth 9' },
		                      
		                      // { path: 'sounds/_horns1/1.mp3', name: 'Horns 1' }, 
		                      // { path: 'sounds/_horns1/2.mp3', name: 'Horns 2' }, 
		                      // { path: 'sounds/_horns1/3.mp3', name: 'Horns 3' }, 
		                      // { path: 'sounds/_horns1/4.mp3', name: 'Horns 4' }, 
		                      // { path: 'sounds/_horns1/5.mp3', name: 'Horns 5' }, 
		                      // { path: 'sounds/_horns1/6.mp3', name: 'Horns 6' }, 
		                      // { path: 'sounds/_horns1/7.mp3', name: 'Horns 7' }, 
		                      // { path: 'sounds/_horns1/8.mp3', name: 'Horns 8' }, 
		                      // { path: 'sounds/_horns1/9.mp3', name: 'Horns 9' }, 
		                      // { path: 'sounds/_horns1/10.mp3', name: 'Horns 10' }, 
		                      // { path: 'sounds/_horns1/11.mp3', name: 'Horns 11' }, 
		                      // { path: 'sounds/_horns1/12.mp3', name: 'Horns 12' }, 
		                      // { path: 'sounds/_horns1/13.mp3', name: 'Horns 13' },
		                       
		                      // { path: 'sounds/_flute1/1.mp3', name: 'Flute 1' }, 
		                      // { path: 'sounds/_flute1/2.mp3', name: 'Flute 2' }, 
		                      // { path: 'sounds/_flute1/3.mp3', name: 'Flute 3' }, 
		                      // { path: 'sounds/_flute1/4.mp3', name: 'Flute 4' }, 
		                      // { path: 'sounds/_flute1/5.mp3', name: 'Flute 5' }, 
		                      // { path: 'sounds/_flute1/6.mp3', name: 'Flute 6' }, 
		                      // { path: 'sounds/_flute1/7.mp3', name: 'Flute 7' }, 
		                      // { path: 'sounds/_flute1/8.mp3', name: 'Flute 8' }, 
		                      // { path: 'sounds/_flute1/9.mp3', name: 'Flute 9' }, 
		                      // { path: 'sounds/_flute1/10.mp3', name: 'Flute 10' }, 
		                      // { path: 'sounds/_flute1/11.mp3', name: 'Flute 11' }, 
		                      // { path: 'sounds/_flute1/12.mp3', name: 'Flute 12' }, 
		                      // { path: 'sounds/_flute1/13.mp3', name: 'Flute 13' }, 
		                        // { path: 'sounds/drum_1.mp3', name: 'Drum 1' },
		                        // { path: 'sounds/drum_2.wav', name: 'Drum 2' },
		                        // { path: 'sounds/hihat.wav', name: 'Hi Hat' },
		                        // { path: 'sounds/snare1.wav', name: 'Snare 1' },
		                        // { path: 'sounds/snare2.wav', name: 'Snare 2' },
		                        { path: 'sounds/fart_1.mp3', name: 'F1' },
		                        // { path: 'sounds/fart_2.mp3', name: 'F2' },
		                        // { path: 'sounds/fart_3.mp3', name: 'F3' },
		                        // { path: 'sounds/fart_4.mp3', name: 'F4' },
		                        { path: 'sounds/fart_5.mp3', name: 'F5' },
		                        // { path: 'sounds/fart_6.mp3', name: 'F6' },
		                        // { path: 'sounds/sangban.wav', name: 'Sangban' },
		                        // { path: 'sounds/tambourine.wav', name: 'Tambourine' }, 
		                        // { path: 'sounds/pop1.wav', name: 'Pop 1' },
		                        // { path: 'sounds/pop2.wav', name: 'Pop 2' },
		                        // { path: 'sounds/maracas1.wav', name: 'Maracas' },
		                        // { path: 'sounds/cowbell.wav', name: 'Cowbell' },
		                        // { path: 'sounds/marimba.mp3', name: 'Marimba 1' },
		                        // { path: 'sounds/marimba2.wav', name: 'Marimba 2' },
		                        // { path: 'sounds/sitar_1.mp3', name: 'Sitar' },
		                        // { path: 'sounds/robotic_1.mp3', name: 'Robotic 1' },
		                        // { path: 'sounds/robotic_2.mp3', name: 'Robotic 2' },
		                        // { path: 'sounds/robotic_3.mp3', name: 'Robotic 3' },
		                        // { path: 'sounds/robotic_4.mp3', name: 'Robotic 4' },
		                        // { path: 'sounds/robotic_5.mp3', name: 'Robotic 5' },
		                        // { path: 'sounds/tuba.mp3', name: 'Tuba' },
		                        // { path: 'sounds/horn_1.mp3', name: 'Horn 1' },
		                        // { path: 'sounds/horn_2.mp3', name: 'Horn 2' },
		                        // { path: 'sounds/horn_3.mp3', name: 'Horn 3' },
		                        // { path: 'sounds/strum_1.mp3', name: 'Strum 1' },
		                        // { path: 'sounds/strum_2.mp3', name: 'Strum 2' },
		                        // { path: 'sounds/kiss_1.mp3', name: 'Kiss' },
		                        // { path: 'sounds/mandolin_01.mp3', name: 'Mandolin 1' },
		                        // { path: 'sounds/mandolin_02.mp3', name: 'Mandolin 2' },
		                        // { path: 'sounds/mandolin_03.mp3', name: 'Mandolin 3' },
		                        // { path: 'sounds/mandolin_04.mp3', name: 'Mandolin 4' },
		                        // { path: 'sounds/mandolin_05.mp3', name: 'Mandolin 5' },
		                        // { path: 'sounds/mandolin_06.mp3', name: 'Mandolin 6' },
		                        // { path: 'sounds/mandolin_07.mp3', name: 'Mandolin 7' },
		                        // { path: 'sounds/mandolin_08.mp3', name: 'Mandolin 8' },
		                        // { path: 'sounds/mandolin_09.mp3', name: 'Mandolin 9' },
		                        // { path: 'sounds/mandolin_10.mp3', name: 'Mandolin 10' },
		                        // { path: 'sounds/mandolin_11.mp3', name: 'Mandolin 11' },
		                        // { path: 'sounds/mandolin_12.mp3', name: 'Mandolin 12' },
		                        // { path: 'sounds/mandolin_13.mp3', name: 'Mandolin 13' },
		                        // { path: 'sounds/mandolin_14.mp3', name: 'Mandolin 14' },
		                        // { path: 'sounds/mandolin_15.mp3', name: 'Mandolin 15' },
		                        // { path: 'sounds/mandolin_16.mp3', name: 'Mandolin 16' },
		                        // { path: 'sounds/mandolin_17.mp3', name: 'Mandolin 17' },
		                        // { path: 'sounds/mandolin_18.mp3', name: 'Mandolin 18' },
		                        // { path: 'sounds/rip_1.mp3', name: 'Cloth Rip 1' },
		                        // { path: 'sounds/rip_2.mp3', name: 'Cloth Rip 2' },
		                        // { path: 'sounds/plywood.mp3', name: 'Plywood' },
		                        // { path: 'sounds/clarinet.wav', name: 'Clarinet' },
		                        // { path: 'sounds/spooky.mp3', name: 'Spooky' }
		                       ]);
		
	}
	
	
	return {
		init: init
	}
});